### ISSUE TITLE
Tidy up breadcrumbs

### ISSUE THREAD

**Issue by m-roberts** [pi-top/DEPRECATED-Peripheral-Configuration#10]
- [ ] Should move initialised device breadcrumbs from home directory
        --> `/etc/pi-top`?
- [ ] Remove ALSA breadcrumb for hifiberry.restore
        --> We should be able to probe ALSA directly for the soundcard device information - no need to pollute the filesystem!

**Comment by benp44** [comment]
Migrated to Device-Management
